stages:          # List of stages for jobs, and their order of execution
  - build
  - sonar

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: alpine
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
  only:
    - master
    - merge_requests

sonarscan-job:
  stage: sonar
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - master
    - merge_requests